spring:
  application:
    name: CourseRegistrationSystem

  datasource:
    url: jdbc:mysql://localhost:3306/appdb
    username: root
    password: Manohar45/
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
